#!/usr/bin/env node

"use strict";

var http = require('http');
var httpProxy = require('./network_simulation/lib/proxy');
var checkServer = require('./network_simulation/lib/check_server');
var nopt = require('nopt');
var url = require('url');

var requests_per_ip = {};
var ip_heat_last = {};
var ip_heat_counter = {};
var req_counter = 0;
var last_successful_req_timestamp = 0;

function isBlacklisted(reqIp) {
  var timestamp = (new Date()).getTime();
  if ((timestamp - last_successful_req_timestamp) > 60) {
    return false;
  } else if (requests_per_ip[reqIp] > 10) {
    return true;
  } else if (ip_heat_last[reqIp] !== undefined && (timestamp - ip_heat_last[reqIp]) < 600 && ip_heat_counter[reqIp] > 8) {
    ip_heat_last[reqIp] = timestamp;
    return true;
  } else {
    return false;
  }
}
function updateBlacklist(reqIp) {
  if (requests_per_ip[reqIp] === undefined) {
    requests_per_ip[reqIp] = 0;
  }
  requests_per_ip[reqIp]++;

  var timestamp = (new Date()).getTime();
  if ((timestamp - ip_heat_last[reqIp]) < 500) {
    if (ip_heat_counter[reqIp] === undefined) {
      ip_heat_counter[reqIp] = 0;
    }
    ip_heat_counter[reqIp]++;
  } else {
    ip_heat_counter[reqIp] = 0;
  }
  ip_heat_last[reqIp] = timestamp;

  last_successful_req_timestamp = timestamp;

  console.log("IP " + reqIp + " now has sent " + requests_per_ip[reqIp] + " reqs; heat is " + ip_heat_counter[reqIp]);
}

var RequestData = function (request, response, buffer) {
  this.request = request;
  this.response = response;
  this.buffer = buffer;
};

function ipFromRequest(reqData) {
  return reqData.request.headers['x-forwarded-for'];
}

function rejectRequest(reqData) {
  reqData.response.writeHead(400);
  reqData.response.end();
}

var Queue = function (proxies, parameters) {
  this.proxies = proxies;
  this.parameters = parameters;
};
Queue.prototype.takeRequest = function (reqData) {
  // Reject traffic as necessary:
  var reqIp = ipFromRequest(reqData);
  if (isBlacklisted(reqIp)) {
    console.log("IP " + reqIp + " REJECTED");
    rejectRequest(reqData);
    return;
  }

  // Otherwise proxy it through:
  updateBlacklist(reqIp);
  req_counter++;
  var proxy_i = req_counter % this.proxies.length;
  this.proxies[proxy_i].proxyRequest(reqData.request, reqData.response, reqData.buffer);
};
Queue.prototype.requestFinished = function () {
  return;
};

function checkBackends(targets, path, response) {
  var toCheck = targets.map(function (target) {
    var output = {};
    output['host'] = target['host'];
    output['port'] = target['port'];
    output['path'] = path;
    return output;
  });
  var success = function () {
    response.writeHead(200, {"Content-Type": "application/json"});
    response.end()
  };
  var error = function () {
    response.writeHead(500, {"Content-Type": "application/json"});
    response.end()
  };
  checkServer.checkServers(toCheck, success, error);
}

function main() {
  var opts = {
    "out-ports": String,
    "in-port": String,
  };
  var parsed = nopt(opts),
      inPort = parsed['in-port'] || '3000',
      outPorts = parsed['out-ports'] ? parsed['out-ports'].split(",") : ['3001'],
      targets = [],
      target,
      proxies = [],
      proxy,
      i;

  for (i = 0; i < outPorts.length; i++) {
    target = {'host': 'localhost', 'port': outPorts[i]};
    targets.push(target);
    proxy = new httpProxy.HttpProxy({'target': target});
    proxy.identifier = i;
    proxies.push(proxy);
  }

  var queue = new Queue(proxies, {});
  for (i = 0; i < proxies.length; i++) {
    proxy = proxies[i];
    proxy.on("end", queue.requestFinished);
  }

  var server = http.createServer(function (req, res) {
    if (req.method === "HEAD") {
      // HEAD requests are used to monitor the status of the simulation
      // proxies[0].proxyRequest(reqData.request, reqData.response, reqData.buffer);
      checkBackends(targets, url.parse(req.url)['pathname'], res);
    } else {
      var buffer = httpProxy.buffer(req);
      var reqData = new RequestData(req, res, buffer);
      queue.takeRequest(reqData);
    }
  });

  server.on('close', function () {
    for (i = 0; i < proxies.length; i++) {
      proxies[i].close();
    }
  });
  console.log("The shield is up and listening.");
  server.listen(inPort);
}

main();
